loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem
  singleBinary:
    enabled: true
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClassName: "" # Use default storage class
      mountPath: /data

  config:
    schema_config:
      configs:
        - from: "2020-10-24"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      filesystem:
        directory: /data/loki/chunks
      tsdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        shared_store: filesystem

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    limits_config:
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 8
      max_cache_freshness_per_query: "10m"

    chunk_store_config:
      max_look_back_period: 24h

    compactor:
      working_directory: /data/loki/compactor
      shared_store: filesystem
      compaction_interval: 10m

# Disable all non-essential components
querier:
  enabled: false
queryFrontend:
  enabled: false
distributor:
  enabled: false
compactor:
  enabled: false
ruler:
  enabled: false
indexGateway:
  enabled: false
gateway:
  enabled: false

# Resource constraints
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi