# values.yaml for fluent-bit Helm chart
namespace: fluent-bit

fullnameOverride: "fluent-bit"

flush: 1
logLevel: debug

config:
  inputs: |
    [INPUT]
        Name         tail
        Path         /var/log/containers/*grammr*.log
        Parser       cri
        Tag          kube.*

  filters: |
    [FILTER]
        Name         kubernetes
        Match        kube.*
        Merge_Log    On
        Keep_Log     Off
        Merge_Log_Key log
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Kube_Tag_Prefix  kube.var.log.containers.
        Annotations      Off
        Labels           On

    [FILTER]
        Name parser
        Match kube.*
        Key_Name log
        Parser java-multiline

  outputs: |
    [OUTPUT]
        name  loki
        match kube.*
        host  loki.monitoring.svc.cluster.local
        labels job=fluent-bit, namespace=$kubernetes['namespace_name'], pod_name=$kubernetes['pod_name'], container_name=$kubernetes['container_name'], app=$kubernetes['labels']['app'], service=$kubernetes['labels']['service']

  customParsers: |
    [PARSER]
        Name        java
        Format      regex
        Regex       ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,3}) (?<level>[^\s]+) (?<message>.*)
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S,%L
        Time_Keep   On
    
    [MULTILINE_PARSER]
        Name          java-multiline
        Type          regex
        Flush_Timeout 1000
        Rule          "^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2} [0-9]{1,2}:[0-9]{1,2}:[0-9]{1,2},[0-9]{3}" "start_state" "cont"
        Rule          "^[^\t]" "cont" "cont"
        Rule          "^\t" "cont" "cont"
        Rule          "^[\\s]+at " "cont" "cont"
        Rule          "^[\\s]+... [0-9]+ more" "cont" "cont"
        Rule          "^[\\s]*Caused by:" "cont" "cont"
